image: gitpod/workspace-postgres

tasks:
  - init: npm run install:all
    command: | 
      npm run build:client
      
ports: 
  - port: 8000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

gihub: 
  prebuilds:
    master: true
    branches: true
    pullRequests: true